services:
  - type: web
    name: stremio-vip-addon
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 7000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ACCESS_TOKEN
        sync: false
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: CLOUDFLARE_R2_ACCESS_KEY_ID
        sync: false
      - key: CLOUDFLARE_R2_SECRET_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_R2_ENDPOINT
        sync: false
      - key: VERCEL_TOKEN
        sync: false
